#!/bin/bash
# Skript pro konverzi .xcf souborů (Gimp) do .djvu
# Původní název souboru - convert.sh
# Dočasná utilita do doby, než bude do nástroje djvutool implementováno vytvoření djvu souboru z obrázku
# TODO:
# - aktuálně se všechny pomocné soubory dělají v tmp

function todjvu {
    RANDOMKEY=$[ 8000 + $[ RANDOM % 1000 ]]
    TEMP_DIR="/tmp/$WINDOWID$BASHPID$RANDOMKEY"
    mkdir $TEMP_DIR
    TEMP_IMG="$TEMP_DIR/temp.ppm"
    TEMP_MASK="$TEMP_DIR/mask.pbm"
    DJVU_MASK="$TEMP_DIR/mask.djvu"

    case ${1##*.} in
	tiff|tif) KONVERT="tifftopnm";;
	png) KONVERT="pngtopnm";;
	jpg) KONVERT="jpegtopnm" ;;
    esac

    #$KONVERT $1 | pnmflip -cw | tee $TEMP_IMG | ppmtopgm | pgmtopbm -threshold -value 0.${3-5} | pnmtoplainpnm > $TEMP_MASK;
    #$KONVERT $1 | pnmflip -r180 | tee $TEMP_IMG | ppmtopgm | pgmtopbm -threshold -value 0.${3-5} | pnmtoplainpnm > $TEMP_MASK;
    $KONVERT $1  | tee $TEMP_IMG | ppmtopgm | pgmtopbm -threshold -value 0.${3-5} | pnmtoplainpnm > $TEMP_MASK;
    cjb2 -lossy -clean $TEMP_MASK $DJVU_MASK;
    djvumake ${1/.png/.djvu} Sjbz=$DJVU_MASK PPM=$TEMP_IMG;
    rm -rf $TEMP_DIR
}

if [ "${1##*.}" == "xcf" ] ; then
    TEMPORARY="/tmp/$WINDOWID$BASHPID"
    mkdir $TEMPORARY
    convert ${1} ${TEMPORARY}/test.png
    pushd $TEMPORARY
    BUNDLE=" "
    for i in $(ls -cr -1) ; do
	todjvu $i
	BUNDLE="$BUNDLE ${i/.png/.djvu}"
    done
    djvm -c out.djvu $BUNDLE
    popd
    mv $TEMPORARY/out.djvu ./
    rm -rf $TEMPORARY
fi
